name: deploy

on:
  push:
    branches:
      - 'public'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install gems
        run: |
          sudo gem install bundler
          sudo gem install middleman -v 4.4.2

      - name: Run deployment script
        shell: bash
        run: |
          chmod +x ./deploy_gh.sh
          ./deploy_gh.sh